[package]
name = "HuwCampbell/optparse-idris"
version = "0.1.2"
authors = []

[dependencies]
"japesinator/Idris-Profunctors" = { git = "https://github.com/clayrat/Idris-Profunctors/" }

[targets.lib]
name = "optparse"
path = "."
mods = ["Options.Applicative"]
idris_opts = ["-p","contrib"]

